# Generated by Django 2.2.5 on 2019-10-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=255)),
                ('tipo_despesa', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('forma_pagamento', models.CharField(max_length=255)),
                ('vencimento', models.DateField(auto_now_add=True)),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
