# Generated by Django 2.2.5 on 2019-10-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='tipo_despesa',
        ),
    ]
