# Generated by Django 2.2.5 on 2019-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_remove_despesa_tipo_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'remedio'), (2, 'roupas'), (3, 'alimentacao'), (4, 'educacao'), (5, 'transporte'), (6, 'outos')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
