# Generated by Django 2.2.5 on 2019-10-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0003_auto_20191023_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Remedio'), (2, 'Roupas'), (3, 'Alimentacao'), (4, 'Educacao'), (5, 'Transporte'), (6, 'Outos')], default=1, max_length=100),
        ),
    ]
