# Generated by Django 2.2.5 on 2019-10-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_auto_20191023_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[(1, 'Dinheiro'), (2, 'Cartão de Crédito'), (3, 'Cartão de Débito'), (4, 'Cartão Crediário'), (5, 'Cheque')], default=1, max_length=255),
        ),
    ]
