# Generated by Django 2.2.5 on 2019-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0005_auto_20191023_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
