# Generated by Django 2.2.5 on 2019-10-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0006_auto_20191023_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateTimeField(),
        ),
    ]
